Miniproyecto_Bertoni_Solutions/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Miniproyecto_Bertoni_Solutions.Models
{
    public class Album
    {
        /*public Album()
        {
            Photos = new List<Photo>();
        }*/
        public int userId { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        //public List<Photo> Photos { get; set; }
    }
}

Miniproyecto_Bertoni_Solutions/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Miniproyecto_Bertoni_Solutions.Models
{
    public class Comment
    {
        public int postId { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string body { get; set; }
    }
}

Miniproyecto_Bertoni_Solutions/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Miniproyecto_Bertoni_Solutions.Models
{
    public class Photo
    {
        /*public Photo()
        {
            Comments = new List<Comment>();
        }*/
        public int albumId { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string thumbnailUrl { get; set; }
        //public List<Comment> Comments { get; set; }
    }
}

Miniproyecto_Bertoni_Solutions/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Miniproyecto_Bertoni_Solutions.Models;
using Miniproyecto_Bertoni_Solutions.Conexion;
using Newtonsoft.Json;

namespace Miniproyecto_Bertoni_Solutions.Controllers
{
    public class AlbumController : Controller
    {
        public ActionResult Index()
        {
            var response = Services.GetAlbums();
            var ListaAlbums = new List<Album>();
            if (response != null)
            {
                ListaAlbums = JsonConvert.DeserializeObject<List<Album>>(response);
            }
            return View(ListaAlbums);
        }
    }
}

Miniproyecto_Bertoni_Solutions/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Miniproyecto_Bertoni_Solutions.Models;
using Miniproyecto_Bertoni_Solutions.Conexion;
using Newtonsoft.Json;

namespace Miniproyecto_Bertoni_Solutions.Controllers
{
    public class CommentController : Controller
    {
        public ActionResult Index(int PhotoId = 0)
        {
            var response = Services.GetComments(PhotoId);
            var ListaComments = new List<Comment>();
            if (response != null)
            {
                ListaComments = JsonConvert.DeserializeObject<List<Comment>>(response);
            }
            return View(ListaComments);
        }
    }
}

Miniproyecto_Bertoni_Solutions/Controllers/HomeController.cs
using Miniproyecto_Bertoni_Solutions.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Miniproyecto_Bertoni_Solutions.Conexion;

namespace Miniproyecto_Bertoni_Solutions.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var response = Services.GetAlbums();
            var ListaAlbums = new List<Album>();
            if (response != null)
            {
                ListaAlbums = JsonConvert.DeserializeObject<List<Album>>(response);
            }
            return View(ListaAlbums);

        }

        public PartialViewResult Photos(int albumId)
        {
            var response = Services.GetPhotos(albumId);
            var ListaPhotos = new List<Photo>();
            if (response != null)
            {
                ListaPhotos = JsonConvert.DeserializeObject<List<Photo>>(response);
            }
            return PartialView(ListaPhotos);
        }


        public PartialViewResult Comments(int photoId)
        {
            HttpWebRequest myReq = (HttpWebRequest)WebRequest.Create("https://jsonplaceholder.typicode.com/comments");
            myReq.ContentType = "application/json";
            var response = (HttpWebResponse)myReq.GetResponse();
            string JSONcomments;

            using (var sr = new StreamReader(response.GetResponseStream()))
            {
                JSONcomments = sr.ReadToEnd();
            }


            var comments = JsonConvert.DeserializeObject<List<Comment>>(JSONcomments);

            return PartialView(comments.Where(x => x.postId == photoId).ToList());
        }

    }
}

Miniproyecto_Bertoni_Solutions/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Miniproyecto_Bertoni_Solutions.Models;
using Miniproyecto_Bertoni_Solutions.Conexion;
using Newtonsoft.Json;

namespace Miniproyecto_Bertoni_Solutions.Controllers
{
    public class PhotoController : Controller
    {
        public ActionResult Index(int AlbumId = 0)
        {
            var response = Services.GetPhotos(AlbumId);
            var ListaPhotos = new List<Photo>();
            if (response != null)
            {
                ListaPhotos = JsonConvert.DeserializeObject<List<Photo>>(response);
            }
            return View(ListaPhotos);
        }

        [HttpPost]
        public ActionResult CargarComments(int PhotoId = 0)
        {
            var response = Services.GetComments(PhotoId);
            var ListaComments = new List<Comment>();

            if (response != null)
            {
                ListaComments = JsonConvert.DeserializeObject<List<Comment>>(response);
            }

            return PartialView("PartialPhotosView", ListaComments);
        }
    }
}

Miniproyecto_Bertoni_Solutions/Views/Album/Index.cshtml
@model IEnumerable<Miniproyecto_Bertoni_Solutions.Models.Album>
@{
    ViewBag.Title = "Album";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Albums</h2>
@if (Model != null && Model.Count() > 0)
{
    <table class="table table-dark">
        <tr>
            <th>
                Id
            </th>
            <th>
                Título
            </th>
            <th>
                Acciones
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    <a href="@Url.Action("Index", "Photo", new { AlbumId = item.id })">Visualizar Album</a>

                </td>
            </tr>
        }
    </table>
}
else
{
    <p> No se encontraron resultados </p>
}

Miniproyecto_Bertoni_Solutions/Views/Comment/Index.cshtml
@model IEnumerable<Miniproyecto_Bertoni_Solutions.Models.Comment>
@{
    ViewBag.Title = "Comments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Comentarios</h2>
@if (Model != null && Model.Count() > 0)
{
    <table class="table table-dark table-bordered">
        <tr>
            <th>
                Id
            </th>
            <th>
                Nombre
            </th>
            <th>
                Email
            </th>
            <th>
                Cuerpo
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.body)
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>No se encontraron resultados</p>
}

Miniproyecto_Bertoni_Solutions/Views/Home/Comments.cshtml
@model IEnumerable<Miniproyecto_Bertoni_Solutions.Models.Comment>

<table class="table table-dark">
    <tr>
        <th>
            Name
        </th>
        <th>
            Email
        </th>
        <th>
            Comment
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => item.body)
            </td>
        </tr>
    }

</table>

Miniproyecto_Bertoni_Solutions/Views/Home/Index.cshtml
@model IList<Miniproyecto_Bertoni_Solutions.Models.Album>
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            Select an Album:
        </div>
        <div class="col-md-4">
            <select name="ddAlbums" id="ddAlbums">
                @foreach (Miniproyecto_Bertoni_Solutions.Models.Album item in Model)
                {
                    <option value="@item.id">@item.title</option>
                }

            </select>
        </div>
        <div class="col-md-4">
            <button id="btnViewAlbum" class="btn btn-dark" >View Album</button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div id="Photos">

            </div>
        </div>
    </div>
        <div class="row">
            <div class="col-md-12">
                <div id="Comments">

                </div>
            </div>
        </div>
</div>
@section Scripts{
    <script type="text/javascript">
        $(function () {
            $("#btnViewAlbum").click(function () {
                $.get("https://" + window.location.host + "/Home/Photos?albumId=" + $("#ddAlbums").val(), function (data) {
                    $("#Photos").html(data);
                    $("#Comments").html("");
                });
            });


        });
    </script>
}

Miniproyecto_Bertoni_Solutions/Views/Home/Photos.cshtml
@model IEnumerable<Miniproyecto_Bertoni_Solutions.Models.Photo>

<table class="table .table-dark">
    <tr>
        <th>
            Title
        </th>
        <th>
            Thumbnail
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                <img src="@item.thumbnailUrl" />
            </td>
            <td>
                <button class="btnComment btn btn-dark"id="@item.id" href="#com">View Comments</button>
            </td>
        </tr>
    }

</table>

<script type="text/javascript">$(function () {
        $(".btnComment").click(function () {
            $.get("https://" + window.location.host + "/Home/Comments?photoId=" + $(this).attr("id"), function (data) {
                $("#Comments").html(data);
            });
        });
    });</script>

Miniproyecto_Bertoni_Solutions/Views/Photo/Index.cshtml
@model IEnumerable<Miniproyecto_Bertoni_Solutions.Models.Photo>
@{
    ViewBag.Title = "Photos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Fotos</h2>
@if (Model != null && Model.Count() > 0)
{
    <table class="table table-dark table-bordered">
        <tr>
            <th>
                Id
            </th>
            <th>
                Título
            </th>
            <th>
                Foto
            </th>
            <th>
                Acciones
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    <img src=@item.url alt=@item.title width="120px" height="120px" />
                </td>
                <td>
                    <input type="button" value="Ver Commentarios" onclick="cargarComments(@item.id)">
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>No se encontraron resultados</p>
}

<input id="IDCargarComments" type="hidden" value="@Url.Action("CargarComments", "Photos")" />

@section Scripts{
    <script type="text/javascript">
        function cargarComments(id) {
            var ParamUrl = $("#IDCargarComments").val() + "?PhotoId=" + id;

            $.ajax({
                url: ParamUrl,
                type: "post",
                data: {
                },
                cache: false,
                success: function (data, textStatus, jqXHR) {
                    $("#Div_comments").html("");
                    $("#Div_comments").html(data);

                    $('#modalComments').modal('show')
                },
                error: function (req, status, error) {
                    alert('Ocurrió un error al cargar la información');
                }
            });
        }
    </script>
}

<div class="modal fade" id="modalComments" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Listado de Comentarios</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="Div_comments">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

Miniproyecto_Bertoni_Solutions/Views/Shared/PartialPhotosView.cshtml
@model List<Miniproyecto_Bertoni_Solutions.Models.Comment>

@{
    Layout = null;
}

@if (Model != null && Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                Id
            </th>
            <th>
                Nombre
            </th>
            <th>
                Email
            </th>
            <th>
                Cuerpo
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.body)
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>No se encontraron resultados</p>
}

Miniproyecto_Bertoni_Solutions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Miniproyecto Album Bertoni Solutions</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top navbar-light" style="background-color: #000000;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Miniproyecto Bertoni Solutions", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Albums", "Index", "Album")</li>
                    <li>@Html.ActionLink("Photos", "Index", "Photo")</li>
                    <li>@Html.ActionLink("Comments", "Index", "Comment")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Miniproyecto Album Bertoni Solutions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>